definitions:
  handler.HealthResponse:
    properties:
      status:
        example: ok
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      description: Returns the health status of the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.HealthResponse'
      summary: Health Check
      tags:
      - health
swagger: "2.0"
